version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - MyTrailer

volumes:
  rabbitmq_data:


networks:
  MyTrailer:
    driver: bridge